version: 2

aliases:
  - &restore_cache
    restore_cache:
      keys:
      - yarn-packages-{{ checksum "yarn.lock" }}

  - &save_cache
    save_cache:
      key: yarn-packages-{{ checksum "yarn.lock" }}
      paths:
        - ~/.cache/yarn

references:
  container_config: &container_config
    docker:
    - image: circleci/node:10.15.1

    working_directory: ~/project

jobs:
  setup:
    <<: *container_config
    steps:
    - checkout
    - *restore_cache
    - run: yarn install --frozen-lockfile
    - *save_cache
    - persist_to_workspace:
        root: ~/project
        paths: .

  build-app:
    <<: *container_config
    steps:
    - attach_workspace:
        at: ~/project
    - run: npm run build

  build-storybook:
    <<: *container_config
    steps:
    - attach_workspace:
        at: ~/project
    - run: npm run storybook:build

  build-packages:
    <<: *container_config
    steps:
    - attach_workspace:
        at: ~/project
    - run: npm run packages-build

  lint-code:
    <<: *container_config
    steps:
    - attach_workspace:
        at: ~/project
    - run: npm run lint

  test-code:
    <<: *container_config
    steps:
    - attach_workspace:
        at: ~/project
    - run: npm run test -- --maxWorkers=2

  cover-code:
    <<: *container_config
    steps:
    - attach_workspace:
        at: ~/project
    - run: npm run coveralls

  update-build-publish-packages_build-deploy-app:
    <<: *container_config
    steps:
    - attach_workspace:
        at: ~/project
    - run: npm run build
    - run: npm run storybook:build
    - add_ssh_keys:
        fingerprints:
        - "8a:e4:f1:cf:c0:07:82:7a:33:c2:4c:94:9c:7b:46:31"
    - run: npm run deploy
    - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ./.npmrc
    - run: npm run packages-publish

workflows:
  version: 2

  branches:
    jobs:
      - setup:
          filters:
            branches:
              ignore:
              - gh-pages
              - master

      - lint-code:
          requires:
          - setup
          filters:
            branches:
              ignore:
              - gh-pages
              - master

      - test-code:
          requires:
          - setup
          filters:
            branches:
              ignore:
              - gh-pages
              - master

      - build-app:
          requires:
          - setup
          filters:
            branches:
              ignore:
              - gh-pages
              - master

      - build-packages:
          requires:
          - setup
          filters:
            branches:
              ignore:
              - gh-pages
              - master

      - build-storybook:
          requires:
          - setup
          filters:
            branches:
              ignore:
              - gh-pages
              - master

  branch-master:
    jobs:
      - setup:
          filters:
            branches:
              only:
              - master

      - lint-code:
          requires:
          - setup
          filters:
            branches:
              only:
              - master

      - cover-code:
          requires:
          - setup
          filters:
            branches:
              only:
              - master

      - update-build-publish-packages_build-deploy-app:
          requires:
          - lint-code
          - cover-code
          filters:
            branches:
              only:
              - master
