version: 2

aliases:
  - &restore_cache
    restore_cache:
      keys:
      - node-dependencies-{{ checksum "package.json" }}

      # fallback to using the latest cache if no exact match is found
      - node-dependencies-

  - &save_cache
    save_cache:
      paths:
      - node_modules

      key: node-dependencies-{{ checksum "package.json" }}

references:
  container_config: &container_config
    docker:
    - image: circleci/node:10.13.0

    working_directory: ~/project

jobs:
  setup:
    <<: *container_config
    steps:
    - checkout
    - *restore_cache
    - run: yarn install
    - *save_cache

  build-app:
    <<: *container_config
    steps:
    - checkout
    - *restore_cache
    - run: yarn install
    - *save_cache
    - run: npm run build

  build-storybook:
    <<: *container_config
    steps:
    - checkout
    - *restore_cache
    - run: yarn install
    - *save_cache
    - run: npm run storybook:build

  lint-code:
    <<: *container_config
    steps:
    - checkout
    - *restore_cache
    - run: yarn install
    - *save_cache
    - run: npm run lint

  test-code:
    <<: *container_config
    steps:
    - checkout
    - *restore_cache
    - run: yarn install
    - *save_cache
    - run: npm run test

  cover-code:
    <<: *container_config
    steps:
    - checkout
    - *restore_cache
    - run: yarn install
    - *save_cache
    - run: npm run coveralls

  update-build-publish-packages_build-deploy-app:
    <<: *container_config
    steps:
    - checkout
    - *restore_cache
    - run: yarn install
    - *save_cache
    - run: npm run build
    - run: npm run storybook:build
    - run: npm run deploy
    - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ./.npmrc
    - run: npm run packages-publish

workflows:
  version: 2

  branches:
    jobs:
      - setup:
          filters:
            branches:
              ignore:
              - gh-pages
              - master

      - lint-code:
          requires:
          - setup
          filters:
            branches:
              ignore:
              - gh-pages
              - master

      - test-code:
          requires:
          - setup
          filters:
            branches:
              ignore:
              - gh-pages
              - master

      - build-app:
          requires:
          - setup
          filters:
            branches:
              ignore:
              - gh-pages
              - master

      - build-storybook:
          requires:
          - setup
          filters:
            branches:
              ignore:
              - gh-pages
              - master

  branch-master:
    jobs:
      - lint-code:
          filters:
            branches:
              only:
              - master

      - cover-code:
          filters:
            branches:
              only:
              - master

      - update-build-publish-packages_build-deploy-app:
          requires:
          - lint-code
          - cover-code
          filters:
            branches:
              only:
              - master
