version: 2

aliases:
  - &restore_cache
    restore_cache:
      keys:
      - node-dependencies-{{ checksum "package.json" }}

      # fallback to using the latest cache if no exact match is found
      - node-dependencies-

  - &save_cache
    save_cache:
      paths:
      - node_modules

      key: node-dependencies-{{ checksum "package.json" }}

references:
  container_config: &container_config
    docker:
    - image: circleci/node:10.13.0

    working_directory: ~/project

jobs:
  lint-and-test:
    <<: *container_config
    steps:
    - checkout
    - *restore_cache
    - run: yarn install
    - *save_cache
    - run: npm run lint
    # - run: npm run test

  update-build-publish-packages_build-deploy-app:
    <<: *container_config
    steps:
    - checkout
    - *restore_cache
    - run: yarn install
    - *save_cache
    - run: npm run build
    - run: npm run storybook:build
    - run: npm run deploy
    - run: npm run packages-publish $NPM_TOKEN

workflows:
  version: 2

  branches:
    jobs:
      - lint-and-test:
          filters:
            branches:
              ignore:
              - gh-pages
              - master

  branch-master:
    jobs:
      - lint-and-test:
          filters:
            branches:
              only:
              - master

      - update-build-publish-packages_build-deploy-app:
          requires:
          - lint-and-test
          filters:
            branches:
              only:
              - master
